### ISSUE TITLE
Clicking the show slider can sometimes close/hide the widget

### ISSUE THREAD

**Issue by DavidSpriggs** [LarryStout/AWAB-Widget-Opacity-Mixin#1]
To reproduce:
1. Open app in desktop browser
2. Open widget
3. Click the black 'show opacity slider' button to show the slider.
4. Grab the slider handle and move it to 0.5 but do not let go of the slider at 0.5
5. keep siding until your cursor is over the widget label text, then let go.
6. This will close the widget, by invoking the header click event.

You might be able to prevent this with an evt.stop() in the slider onChange handler.

**Comment by LarryStout** [comment]
I'm clueless.  Firefox doesn't exhibit this behavior, and I've tried all of the event rigging I know how to do in Chrome, but the problem persists.  I already had a click event handler on the slider with an evt.stopImmediatePropagation() call.  The change event on the slider returns a value, not an event, so I can't use that trick there.  I'm guessing the widget events in the stem app are defeating me at every turn.
